### ISSUE TITLE
Katana throws error on Kubernetes

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-docker-images#30]
running katana on minikube with k8s throws this error in the Vamp container logs:

```
2017-03-21T07:52:40.601072535Z 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
2017-03-21T07:52:40.601139070Z 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
2017-03-21T07:52:40.601210383Z 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
2017-03-21T07:52:40.601353516Z 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
2017-03-21T07:52:40.601424643Z 	at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:74)
2017-03-21T07:52:40.601490623Z 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:64)
2017-03-21T07:52:40.601566728Z 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:37)
2017-03-21T07:52:40.601636135Z 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:213)
2017-03-21T07:52:40.601709218Z 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:181)
2017-03-21T07:52:40.601775703Z 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:305)
2017-03-21T07:52:40.601845308Z 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:302)
2017-03-21T07:52:40.601911543Z 	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
2017-03-21T07:52:40.602366320Z 	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
2017-03-21T07:52:40.602455688Z 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:302)
2017-03-21T07:52:40.602542981Z 	at akka.actor.ActorSystem$.$anonfun$apply$4(ActorSystem.scala:242)
2017-03-21T07:52:40.602619753Z 	at scala.Option.getOrElse(Option.scala:121)
2017-03-21T07:52:40.602695563Z 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:242)
2017-03-21T07:52:40.602771623Z 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:288)
2017-03-21T07:52:40.602847800Z 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:233)
2017-03-21T07:52:40.602980711Z 	at io.vamp.bootstrap.Vamp.$init$(Vamp.scala:13)
2017-03-21T07:52:40.603068548Z 	at io.vamp.bootstrap.Boot$.<init>(Boot.scala:3)
2017-03-21T07:52:40.603133313Z 	at io.vamp.bootstrap.Boot$.<clinit>(Boot.scala)
2017-03-21T07:52:40.603215648Z 	... 1 more
2017-03-21T07:52:46.760052840Z Exception in thread "main" java.lang.ExceptionInInitializerError
2017-03-21T07:52:46.760222720Z 	at io.vamp.bootstrap.Boot.main(Boot.scala)
2017-03-21T07:52:46.760504405Z Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: /usr/local/vamp/conf/application.conf: 44: Could not resolve substitution to a value: ${vamp_url}
```

**Comment by ItsMeijers** [comment]
Solved by https://github.com/magneticio/vamp-lifter/commit/343660f8529b7ea1c645e15a25d9a4611599a2cf
